/*
 * This file is part of the ESO Common Pipeline Library
 * Copyright (C) 2001-2017 European Southern Observatory
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

/*
 * Do not edit this file! This file was automatically generated.
 * All changes to this file might be lost!
 */

#ifndef CPL_VERSION_H
#define CPL_VERSION_H

#include <cpl_macros.h>


#define CPL_VERSION_STRING "7.1"
#define CPL_VERSION_CODE 459008

#define CPL_VERSION(major, minor, micro) \
(((major) * 65536) + ((minor) * 256) + (micro))



CPL_BEGIN_DECLS

unsigned int cpl_version_get_major(void) CPL_ATTR_CONST;
unsigned int cpl_version_get_minor(void) CPL_ATTR_CONST;
unsigned int cpl_version_get_micro(void) CPL_ATTR_CONST;

unsigned int cpl_version_get_interface_age(void) CPL_ATTR_CONST;
unsigned int cpl_version_get_binary_age(void) CPL_ATTR_CONST;

const char *cpl_version_get_version(void) CPL_ATTR_CONST;
unsigned int cpl_version_get_binary_version(void) CPL_ATTR_CONST;

CPL_END_DECLS

#endif /* CPL_VERSION_H */
